package com.borderless.ankicards.domain.recipe

/**
 * The catalog of built-in field blocks shown in the card-builder palette.
 *
 * Each preset is a function (not a value) so callers get a fresh [CardField]
 * to drop into their card type — mutations from one place don't leak to
 * another. Defaults are chosen to be sensible for the most common use case
 * (language learning) while remaining easy to override in the per-field
 * settings panel.
 *
 * To add a new preset: define a new function here, and add it to the palette
 * grouping in [FieldPresetCatalog].
 */
object FieldPresets {

    // ----- Core (universal) fields -----

    /**
     * The canonical form of the word being learned, in the target language.
     *
     * Generated by the LLM from the user's query so that disambiguation hints
     * in the query (e.g. "evening je6maan5" to specify the 夜晚 sense, not
     * 晚黑) get resolved into one specific word. Dictionary lookups on other
     * fields key off this resolved value, not the raw user input.
     */
    fun word() = CardField(
        key = "word",
        label = "Word",
        description = "The canonical word or term being learned, in the target language. " +
            "Resolve any disambiguation hints in the user's query (such as a specific " +
            "romanization or English gloss they included) into a single canonical form.",
        generator = FieldGenerator.Llm(),
        required = true
    )

    /**
     * Bare English gloss for the word. Sits on every language preset's
     * back face as the "what does this mean" answer. Distinct from
     * [definition] (which is sentence-form) — this is intentionally short
     * so a card glance gives an immediate translation.
     *
     * Naming note: this is hard-coded to English rather than "user's
     * native language" because the app currently has no UI for setting
     * the user's language. If a non-English variant ever ships, this
     * field gets generalized along with that UI.
     */
    fun english() = CardField(
        key = "english",
        label = "English",
        description = "The English translation of the word. A short bare gloss " +
            "(one or two senses, separated by '; ' if multiple). Not a sentence " +
            "or a definition — just the English equivalent(s).",
        generator = FieldGenerator.Llm()
    )

    fun definition() = CardField(
        key = "definition",
        label = "Definition",
        description = "A short, clear definition of the word (one or two senses, " +
            "not an exhaustive dictionary entry).",
        generator = FieldGenerator.Llm()
    )

    fun exampleSentence() = CardField(
        key = "example",
        label = "Example Sentence",
        description = "A short natural example sentence that contains the exact word from " +
            "the `word` field in its original written form — not a synonym or colloquial variant. " +
            "For languages written in a non-Latin script (Mandarin, Cantonese, " +
            "Japanese, Thai), return EXACTLY THREE lines, separated by real " +
            "`\\n` newline characters in the JSON string value. ALL THREE LINES " +
            "ARE REQUIRED — skipping the romanization line is wrong.\n" +
            "\n" +
            "LINE 1: the sentence in the target language\n" +
            "LINE 2: full romanization of line 1 — Pinyin with tone marks for " +
            "Mandarin (e.g. 'zhè zhī cāngyíng zhēn fán rén'), Jyutping with " +
            "tone NUMBERS for Cantonese (e.g. 'ni1 zek3 wu1 jing1 hou2 faan4'), " +
            "Furigana / kana reading for Japanese, phonetic romanization with " +
            "tones for Thai.\n" +
            "LINE 3: the English translation\n" +
            "\n" +
            "For Latin-script languages (Spanish, French, German, Italian, " +
            "Generic): return only TWO lines — the sentence then the English " +
            "translation. No romanization line.\n" +
            "\n" +
            "Example output for the Mandarin word 苍蝇 (use real line breaks " +
            "inside the JSON string, shown here as visible newlines):\n" +
            "这只苍蝇真烦人。\n" +
            "zhè zhī cāngyíng zhēn fán rén.\n" +
            "This fly is so annoying.",
        generator = FieldGenerator.Llm()
    )

    fun image(style: String = "realistic photo") = CardField(
        key = "image",
        label = "Image",
        description = "A visual representation of the word's meaning.",
        generator = FieldGenerator.ImageGen(style = style)
    )

    /**
     * TTS audio for one of the card's other fields. Default source is
     * `word` — for vocab cards, the user almost always wants to hear how
     * the target-language word is pronounced. Callers can override (e.g.
     * `sourceFieldKey = "example"`) for sentence-level audio.
     */
    fun audio(sourceFieldKey: String = "word") = CardField(
        key = "audio",
        label = "Audio",
        description = "Spoken audio for the source field, generated via TTS.",
        generator = FieldGenerator.Tts(sourceFieldKey = sourceFieldKey)
    )

    // ----- Cantonese -----

    fun jyutping() = CardField(
        key = "jyutping",
        label = "Jyutping",
        description = "Cantonese romanization in Jyutping with tone numbers.",
        generator = FieldGenerator.Dictionary(source = DictionarySource.CC_CANTO)
    )

    fun cantoneseMeasureWord() = CardField(
        key = "measure_word",
        label = "Measure Word",
        description = "The classifier / measure word commonly used with this noun. " +
            "Format: '<character> <jyutping>' — e.g. '個 go3' or '隻 zek3'.",
        generator = FieldGenerator.Dictionary(source = DictionarySource.CC_CANTO)
    )

    // ----- Mandarin -----

    fun pinyin() = CardField(
        key = "pinyin",
        label = "Pinyin",
        description = "Mandarin romanization in Pinyin with tone marks.",
        generator = FieldGenerator.Dictionary(source = DictionarySource.CC_CEDICT)
    )

    fun mandarinMeasureWord() = CardField(
        key = "measure_word",
        label = "Measure Word",
        description = "The classifier / measure word commonly used with this noun in Mandarin. " +
            "Format: '<character> <pinyin>' — e.g. '个 gè' or '只 zhī'. " +
            "Use simplified Chinese for the character.",
        generator = FieldGenerator.Dictionary(source = DictionarySource.CC_CEDICT)
    )

    // ----- Japanese -----

    fun furigana() = CardField(
        key = "furigana",
        label = "Furigana",
        description = "Hiragana reading shown above the kanji.",
        generator = FieldGenerator.Dictionary(source = DictionarySource.JMDICT)
    )

    fun pitchAccent() = CardField(
        key = "pitch_accent",
        label = "Pitch Accent",
        description = "Tokyo-dialect pitch-accent pattern for this word.",
        generator = FieldGenerator.Llm()
    )

    // ----- Thai -----

    fun thaiRomanization() = CardField(
        key = "romanization",
        label = "Romanization",
        description = "Phonetic romanization of the Thai word, including tone information.",
        generator = FieldGenerator.Llm()
    )

    fun thaiClassifier() = CardField(
        key = "measure_word",
        label = "Classifier",
        description = "The Thai classifier commonly used to count this noun. " +
            "Format: '<Thai script> <romanization>'.",
        generator = FieldGenerator.Llm()
    )

    // ----- European-language helpers -----

    fun gender() = CardField(
        key = "gender",
        label = "Gender",
        description = "Grammatical gender of the noun (e.g. masculine / feminine / neuter).",
        generator = FieldGenerator.Llm()
    )

    fun pluralForm() = CardField(
        key = "plural",
        label = "Plural",
        description = "The plural form of this noun.",
        generator = FieldGenerator.Llm()
    )

    // ----- Extras -----

    fun mnemonic() = CardField(
        key = "mnemonic",
        label = "Mnemonic",
        description = "A vivid mental image or wordplay that makes this word easier to remember.",
        generator = FieldGenerator.Llm()
    )

    fun partOfSpeech() = CardField(
        key = "part_of_speech",
        label = "Part of Speech",
        description = "Noun / verb / adjective / adverb / etc.",
        generator = FieldGenerator.Llm()
    )

    fun etymology() = CardField(
        key = "etymology",
        label = "Etymology",
        description = "A brief note on the word's origin or root.",
        generator = FieldGenerator.Llm()
    )

    /**
     * A blank custom field for the user to fill in. The card-builder palette
     * surfaces this as a special "+ Custom field" block: dropping it on the
     * card opens an editor for the user to set [CardField.key],
     * [CardField.label], and [CardField.description] before save.
     *
     * Defaults to LLM generation since the whole point of a custom field is
     * "describe what you want and AI fills it in."
     */
    fun customField(
        key: String,
        label: String,
        description: String
    ) = CardField(
        key = key,
        label = label,
        description = description,
        generator = FieldGenerator.Llm()
    )
}

/**
 * Grouped catalog of presets for the palette UI. Each group becomes a section
 * header in the drag-and-drop palette. Order within a group is the order
 * shown on screen.
 */
object FieldPresetCatalog {

    data class PresetEntry(val displayName: String, val build: () -> CardField)
    data class PresetGroup(val title: String, val entries: List<PresetEntry>)

    val core = PresetGroup(
        title = "Core",
        entries = listOf(
            PresetEntry("Word") { FieldPresets.word() },
            PresetEntry("English") { FieldPresets.english() },
            // Definition is still available via FieldPresets.definition()
            // for users who want to add it manually, but it's not in the
            // default palette anymore — the language presets stopped
            // shipping it and the user explicitly didn't want it cluttering
            // the New-Field picker.
            PresetEntry("Example sentence") { FieldPresets.exampleSentence() },
            PresetEntry("Image") { FieldPresets.image() },
            PresetEntry("Audio (TTS)") { FieldPresets.audio() }
        )
    )

    val cantonese = PresetGroup(
        title = "Cantonese",
        entries = listOf(
            PresetEntry("Jyutping") { FieldPresets.jyutping() },
            PresetEntry("Measure word") { FieldPresets.cantoneseMeasureWord() }
        )
    )

    val mandarin = PresetGroup(
        title = "Mandarin",
        entries = listOf(
            PresetEntry("Pinyin") { FieldPresets.pinyin() },
            PresetEntry("Measure word") { FieldPresets.mandarinMeasureWord() }
        )
    )

    val japanese = PresetGroup(
        title = "Japanese",
        entries = listOf(
            PresetEntry("Furigana") { FieldPresets.furigana() },
            PresetEntry("Pitch accent") { FieldPresets.pitchAccent() }
        )
    )

    val thai = PresetGroup(
        title = "Thai",
        entries = listOf(
            PresetEntry("Romanization") { FieldPresets.thaiRomanization() },
            PresetEntry("Classifier") { FieldPresets.thaiClassifier() }
        )
    )

    val european = PresetGroup(
        title = "European languages",
        entries = listOf(
            PresetEntry("Gender") { FieldPresets.gender() },
            PresetEntry("Plural") { FieldPresets.pluralForm() }
        )
    )

    val extras = PresetGroup(
        title = "Extras",
        entries = listOf(
            PresetEntry("Mnemonic") { FieldPresets.mnemonic() },
            PresetEntry("Part of speech") { FieldPresets.partOfSpeech() },
            PresetEntry("Etymology") { FieldPresets.etymology() }
        )
    )

    /** All preset groups in their display order in the palette. */
    val all: List<PresetGroup> = listOf(core, cantonese, mandarin, japanese, thai, european, extras)

    /**
     * Groups relevant to a card type's [language] — used by the card
     * designer's palette so users don't see e.g. Jyutping chips while
     * editing a Spanish card. Always returns Core + Extras (universal),
     * plus the single language-specific group matching the card.
     *
     * Language codes match the BCP-47-ish ones on `DeckLanguage`:
     * `yue` Cantonese, `cmn` Mandarin, `ja` Japanese, `th` Thai,
     * `es`/`fr`/`de`/`it` European. Generic / unknown / null → no
     * language-specific group surfaces.
     */
    fun forLanguage(language: String?): List<PresetGroup> {
        val languageSpecific = when (language) {
            "yue" -> cantonese
            "cmn" -> mandarin
            "ja" -> japanese
            "th" -> thai
            "es", "fr", "de", "it" -> european
            else -> null
        }
        return listOfNotNull(core, languageSpecific, extras)
    }
}
